package dev.chouten.runners.relay

import kotlinx.cinterop.*
import relay.*   // generated by cinterop

actual object NativeBridge {
    actual fun load(bytes: ByteArray) {
        bytes.usePinned { pinned ->
            relay_load_wasm(
                pinned.addressOf(0),
                bytes.size
            )
        }
    }

    actual fun add(a: Int, b: Int): Int {
        return relay_add(a, b)
    }

    actual fun initLogger(logger: Any) {
        val stableRef = StableRef.create(logger)
        relay_init_logger(stableRef.asCPointer())
    }
}
